	//gameconfig
	var config = {
		startPop: 6,
		costWall:2,
		costTower:8,
		costCastle:24,
		costHome:2,
		costTreasury:20,
		costGallows:50,
		costFountain:50,
		costStash:50,
		costInn:20,
		costStable:50,
		costSmith:50,
		costArchery:50,
		bldUniversityCost: 200,
		lotteryPrize:50,
		treasuryGuardPriceHire:20,
		treasuryGuardPricePayroll:10,
		costPutOutFire:20,
		sizeMapX:18,//18
		sizeScrX:16,//16
		sizeMapY:18,//18
		sizeScrY:10,//10
		costHero:20,
		heroExpK:5,
		festPrice:2,
		festCooldown:30,
		glSaveVersion:9,
		genMapCostBasic:50,
		// fireStepsBasic:60,
		oneSecMS:1000,
		sergeantHiring:20,
		sergeantUpkeep:5,
		turkopolHiring:20,
		turkopolUpkeep:5,
		knightHiring:40,
		knightUpkeep:8,
		chestMoney:25,
		chestCity_timeout:15000,//ms
		chestCity:50,
		maxLevelHome: 40,
		maxLevelTreasury: -1, //Not limited
		maxLevelStash: -1, //Not limited
		maxLevelGallows: 10,
		maxLevelFountain: 10,
		maxLevelInn: 10,
		maxLevelStable: 3,
		maxLevelArchery: 3,
		maxLevelUniversity: 1,
		tutorialDefenseEventTicks: 3,
		tutNewBuildingsT: 5,
		tutTreasuryG: 200,
		tutAutoSaveT: 10,
		tutStablesP: 40,
		tutArcheryP: 60,
		tutInnP: 80,
		tutSocialP: 100,
		isOnline: true,
		pullMessages: true,
		pullMessagesMS: 1500,
		debug: false,
		theme: "winter",
		artilleryResearchCost: 200,
		popIncRate: 2,
	};