var artefacts = {
    artid00: {
        id: "artid00",
        img: "scroll_01.png",
        name: localeStrings[286],
        desc: localeStrings[287],
        attr: [],
        change: [],
        priceBuy: 500,
        chance: 1,
        type: "scrolls",
    },
    artid01: {
        id: "artid01",
        name: localeStrings[288],
        desc: localeStrings[289],
        attr: ["luck","superstition"],
        change: [1,1],
        priceBuy: 1500000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid02: {
        id: "artid02",
        name: localeStrings[290],
        desc: localeStrings[291],
        attr: ["moral"],
        change: [1],
        priceBuy: 1500000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid03: {
        id: "artid03",
        name: localeStrings[292],
        desc: localeStrings[293],
        attr: ["moral"],
        change: [1],
        priceBuy: 1500000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid04: {
        id: "artid04",
        name: localeStrings[294],
        desc: localeStrings[295],
        attr: ["moral"],
        change: [1],
        priceBuy: 1500000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid05: {
        id: "artid05",
        name: localeStrings[296],
        desc: localeStrings[297],
        attr: ["moral"],
        change: [1],
        priceBuy: 1500000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid06: {
        id: "artid06",
        name: localeStrings[298],
        desc: localeStrings[299],
        attr: ["luck","superstition"],
        change: [1,1],
        priceBuy: 1500000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid07: {
        id: "artid07",
        name: localeStrings[300],
        desc: localeStrings[301],
        attr: ["luck","superstition"],
        change: [1,1],
        priceBuy: 1500000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid08: {
        id: "artid08",
        name: localeStrings[302],
        desc: localeStrings[303],
        attr: ["luck","superstition"],
        change: [1,1],
        priceBuy: 1500000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid09: {
        id: "artid09",
        name: localeStrings[304],
        desc: localeStrings[305],
        attr: ["luck","superstition"],
        change: [0,0],
        priceBuy: 1500000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid10: {
        id: "artid10",
        name: localeStrings[306],
        desc: localeStrings[307],
        attr: [],
        change: [],
        priceBuy: 5000000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid11: {
        id: "artid11",
        img: "glyph_01.png",
        name: locObj.glyphKnightTile.txt,
        desc: locObj.glyphKnightDesc.txt,
        attr: [
            { name: "atk", type: "flat", val: 10 },
            { name: "def", type: "flat", val: 6 }
        ],
        change: [],
        priceBuy: 5000000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid12: {
        id: "artid12",
        img: "glyph_02.png",
        name: locObj.glyphMonkTile.txt,
        desc: locObj.glyphMonkDesc.txt,
        attr: [
            { name: "atk", type: "flat", val: 4 },
            { name: "def", type: "flat", val: 12 }
        ],
        change: [],
        priceBuy: 5000000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1,
    },
    artid13: {
        id: "artid13",
        img: "rune_gold.png",
        name: locObj.goldRuneTitle.txt,
        desc: locObj.goldRuneTitle.txt,
        attr: [{name: "gold", type: "percentage", val: 1.07}],
        change: [],
        priceBuy: 5000000,
        chance: 1,
        type: "artefactsWorn",
        artefactsWorn: 1
    }
};

Object.freeze(artefacts);