name: "Unit tests"

on:
  pull_request:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  smoke_job:
    name: Cypress unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: cypress run
        uses: cypress-io/github-action@v5      
        with:
          working-directory: tests/tests_cypress/unit
          run: npm install chai-json-schema
          start: npm run start
